version: '3.8'
networks:
  babnet:
    ipam:
      config:
        - subnet: 172.20.0.0/23

services:
  uhrp-server:
    hostname: 'uhrp-server'
    build: .
    # volumes:
    #     - ".:/app"
    #   - "./src:/app/src"
    ports:
      - "8080:8080"
      - "9229:9229"
    networks:
      - babnet
    environment:
      MIGRATE_KEY: 'my-great-key'
      NODE_ENV: 'development'
      HOSTING_DOMAIN: 'http://localhost:8080'
      WALLET_STORAGE_URL: 'https://staging-storage.babbage.systems'
      ADMIN_TOKEN: 'admin-token'
      HTTP_PORT: 8080
      PRICE_PER_GB_MO: 0.03
      UHRP_HOST_PRIVATE_KEY: '5KKGHf1dZpJ1L4aQTGCrVL4q3y5iwbcf9YcWS3oXynrWjaxS2LD'
      SERVER_PRIVATE_KEY: 'ab93af021feaab26a9adff360fc8a32da645539985a0adfcc2cecbfe76bb4e41'
      SERVER_XPRIV: 'xprv9s21ZrQH143K3GN3VANh6bt72CgqhysD35WrbZWq7zJMg9Jegv7qPhgCy1To8PHW8fJoa4EDLCx73FK8Ljfg64mW9XK9g13xkMwZKQPWZ9Y'
      MIN_HOSTING_MINUTES: 15
      GCP_BUCKET_NAME: 'staging-uhrp'
      GCP_PROJECT_ID: 'babbage-uhrp'
      GOOGLE_APPLICATION_CREDENTIALS: '/app/service-account.json'
    command: npm run dev

